name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu

    - name: build cobalt
      working-directory: Cobalt
      run: ./gradlew publishToMavenLocal --no-daemon

    - name: build cc-tweaked
      working-directory: CC-Tweaked
      run: ./gradlew publishToMavenLocal --no-daemon

    - name: build ccemux
      working-directory: CCEmuX
      run: ./gradlew build --no-daemon
