name: Build

on: [push, pull_request]

concurrency:
  group: monorepo-ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: zulu

    - name: setup gradle
      uses: gradle/actions/setup-gradle@v4

    - name: build cobalt
      working-directory: Cobalt
      run: ./gradlew publishToMavenLocal --no-daemon

    - name: build cc-tweaked
      working-directory: CC-Tweaked
      run: ./gradlew publishToMavenLocal --no-daemon

    - name: build ccemux
      working-directory: CCEmuX
      run: ./gradlew build --no-daemon

    - name: upload artifact
      if: ${{ always() }}
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: build artifacts
        path: |
          */build/libs/*.jar

    - name: delete release
      if: ${{ github.ref_name == 'main' }}
      continue-on-error: true
      run: gh release delete latest --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: rename jar
      if: ${{ github.ref_name == 'main' }}
      run: mv CCEmuX/build/libs/CCEmuX*-cct.jar ciemux.jar

    - name: create release
      if: ${{ github.ref_name == 'main' }}
      uses: softprops/action-gh-release@v2
      id: create-release
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          ciemux.jar
        name: ciemux
        prerelease: false
        tag_name: latest

    - name: publish release
      if: ${{ github.ref_name == 'main' }}
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        release_id: ${{ steps.create-release.outputs.id }}

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install act
      run: curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
    - name: run act
      run: act -W gh-test/.github/workflows/sample.yml
