name: Build

on: [push, pull_request]

concurrency:
  group: monorepo-ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install java
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: zulu

    - name: setup gradle
      uses: gradle/actions/setup-gradle@v3

    - name: build cobalt
      working-directory: Cobalt
      run: ./gradlew publishToMavenLocal --no-daemon

    - name: build cc-tweaked
      working-directory: CC-Tweaked
      run: ./gradlew publishToMavenLocal --no-daemon

    - name: build ccemux
      working-directory: CCEmuX
      run: ./gradlew build --no-daemon

    - name: delete release
      continue-on-error: true
      run: gh release delete latest --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: create release
      uses: softprops/action-gh-release@v2
      id: create-release
      with:
        draft: true
        fail_on_unmatched_files: true
        files: |
          CCEmuX/build/libs/CCEmuX*.jar
        name: ciemux
        prerelease: false
        tag_name: latest

    - name: publish release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        release_id: ${{ steps.create-release.outputs.id }}
